
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALL AND CARDINALITY CLASS EXACTLY IDENT_LPAREN INDIVIDUAL KEYWORD LPAREN MAX MIN NAMESPACE NOT NUMERAL OR PROPERTY RPAREN SOME SPECIAL_SYMBOL THAT TWOPOINTS TYPE VALUEprimitive_class : KEYWORD TWOPOINTS CLASS primitive_class\n                       | empty\n    empty :'
    
_lr_action_items = {'KEYWORD':([0,5,],[2,2,]),'$end':([0,1,3,5,6,],[-3,0,-2,-3,-1,]),'TWOPOINTS':([2,],[4,]),'CLASS':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'primitive_class':([0,5,],[1,6,]),'empty':([0,5,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> primitive_class","S'",1,None,None,None),
  ('primitive_class -> KEYWORD TWOPOINTS CLASS primitive_class','primitive_class',4,'p_primitive_class','osa.py',29),
  ('primitive_class -> empty','primitive_class',1,'p_primitive_class','osa.py',30),
  ('empty -> <empty>','empty',0,'p_empty','osa.py',63),
]
